#font customization
font_family CaskaydiaCove Nerd Font
font_size                     13.0

#basic settings
enable_audio_bell             no
disable_ligatures             no
confirm_os_window_close       0
sync_to_monitor               no

#shell customization
shell                         zsh
shell_integration             disabled

#cursor customization
cursor_shape                  block
cursor_blink_interval         0
#url customization
url_style                     curly

#Window customization
remember_window_size          no
window_padding_width          30

#Visual customization
background #2C3038
foreground #E6E0D1
background_opacity            0.85
scrollbar_handle_opacity      0.00
scrollbar_track_opacity       0.00
scrollbar_track_hover_opacity 0.00
